js/package.json, js/src/internal/polyfill/aes.ts, js/src/internal/util.ts, js/src/sivchain.ts, js/test/sivchain.spec.ts, js/tsconfig.json, js/yarn.lock
Changes the `AESSIV` API to be asynchronous and promised-based.
This is futureproofing for a potential switch to WebCrypto. WebCrypto uses
asynchronous APIs everywhere (which, IMO, is a tad silly for cryptographic
primitives that finish in nanoseconds, but que sera sera).
=> js: Promise-based AES-SIV API

.travis.yml, js/package.json, js/test/aes_ctr.spec.ts, js/test/aes_siv.spec.ts, js/yarn.lock
The node-webcrypto-ossl library provides an implementation of the WebCrypto API
based on OpenSSL.
They recently added AES-CTR support, so we can use this to test our
WebCrypto-based implementation of AES-CTR works correctly.
=> js: Test WebCrypto AES-CTR with node-webcrypto-ossl

js/src/internal/polyfill/aes.ts, js/test/aes.spec.ts
Neither AES-CTR or AES-CMAC require the AES decrypt function, so we can remove it.
=> js: Remove AES decrypt function

README.md, js/README.md, js/src/internal/aes_siv.ts, js/src/internal/constant-time.ts, js/src/internal/interfaces.ts, js/src/internal/polyfill/aes.ts, js/src/internal/polyfill/aes_cmac.ts, js/src/internal/polyfill/aes_ctr.ts, js/src/internal/webcrypto/aes_cmac.ts, js/src/internal/webcrypto/aes_ctr.ts, js/test/aes.spec.ts, js/test/aes_cmac.spec.ts, js/test/aes_ctr.spec.ts, js/test/constant-time.spec.ts
This commit adds a `WebCryptoAesCmac` implementation as an alternative to `PolyfillAesCmac`, which is built using an AES-ECB-like wrapper on top of CBC mode (i.e. use an IV of all zeroes and take the first block of CBC mode output)
This could be further refined to use CBC mode to process multiple blocks instead of just one, which should improve performance. This commit is just a first pass.
=> js: Web Crypto support for AES-CMAC

js/README.md, js/src/internal/aes_siv.ts, js/src/internal/polyfill.ts, js/src/sivchain.ts, js/test/aes_siv.spec.ts, js/test/sivchain.spec.ts
This replaces the very implicit "just pass null" API to use polyfills with one
which clearly labels their usage in the context of the API.
This should hopefully make it harder to overlook the usage of polyfills, which
are not constant time.
=> js: Explicit SIV.getCryptoProvider("polyfill") API

README.md
Per Rogaway, AES-GCM-SIV should probably have a green heart too.
This reverts 10ba81a804225ada2b0c5503ef2f0194f43f7f80
=> README.md: Revert AES-GCM-SIV heart color back to green

.travis.yml, rust/Cargo.lock, rust/Cargo.toml, rust/README.md, rust/src/internals/aes.rs, rust/src/internals/block.rs, rust/src/internals/block_cipher.rs, rust/src/internals/cmac.rs, rust/src/internals/ctr.rs, rust/src/internals/mod.rs, rust/src/internals/util/dbl.asm, rust/src/internals/util/dbl.rs, rust/src/internals/util/mod.rs, rust/src/lib.rs, rust/src/siv.rs, rust/tests/lib.rs, rust/tests/test_vectors.rs, vectors/aes_ctr.tjson
This commit implements AES-CMAC, AES-CTR, and AES-SIV using the `aesni` crate.
The implementation presently only works on nightly, and leverages a number of nightly features including inline assembly, intrinisics, and `repr_align` to ensure alignment of blocks in memory.
=> rust: Initial implementation based on the aesni crate

rust/Cargo.lock, rust/Cargo.toml, rust/src/internals/block.rs, rust/src/siv.rs
subtle 0.2.0 is tagged and ready to release, but it hasn't been released yet.
For now downgrade to 0.1.1, and then we can revert this comment to upgrade to 0.2.0 once it's been released.
=> rust: Downgrade subtle crate to 0.1.0

rust/Cargo.lock, rust/Cargo.toml, rust/src/internals/block.rs, rust/src/siv.rs
Upgrades subtle to version 0.2.0.
This reverts commit 6608c03f90f152da251773baffdbcc0bd6b44432.
=> Revert "rust: Downgrade subtle crate to 0.1.0"

rust/src/siv.rs, rust/tests/lib.rs
Previously the `seal_in_place()`/`open_in_place()` functions copied the plaintext to/from the beginning/end of the buffer.
Instead we can simply make the API contract to place the plaintext at the end of the buffer so we can avoid copying it.
=> rust: Avoid needless copying

rust/Cargo.lock, rust/Cargo.toml, rust/README.md, rust/src/internals/block.rs, rust/src/internals/cmac.rs, rust/src/internals/ctr.rs, rust/src/lib.rs
Following in the footsteps of #42, this commit removes any remaining unsafe code in the implementation, replacing it with safe code or third-party crates which wrap up unsafe functionality for us.
Use of any unsafe code should have a concrete justification, e.g. ensuring constant time operation or significant performance improvements.
Unfortunately, we can't actually `#[deny(unsafe_code)]` because the `array_ref!` crate generates some. Hopefully with future type system improvements we can get rid of `array_ref!` and actually turn on `#[deny(unsafe_code)]`.
=> rust: Remove all unsafe code

rust/Cargo.lock, rust/Cargo.toml, rust/src/bench.rs, rust/src/lib.rs
Current results:
```
test bench::bench_aes_gcm_128_encrypt_1024_bytes  ... bench:         306 ns/iter (+/- 80) = 3346 MB/s
test bench::bench_aes_gcm_128_encrypt_128_bytes   ... bench:         114 ns/iter (+/- 36) = 1122 MB/s
test bench::bench_aes_gcm_128_encrypt_16384_bytes ... bench:       3,494 ns/iter (+/- 1,187) = 4689 MB/s
test bench::bench_aes_siv_128_encrypt_1024_bytes  ... bench:       3,148 ns/iter (+/- 386) = 325 MB/s
test bench::bench_aes_siv_128_encrypt_128_bytes   ... bench:         485 ns/iter (+/- 67) = 263 MB/s
test bench::bench_aes_siv_128_encrypt_16384_bytes ... bench:      44,556 ns/iter (+/- 9,683) = 367 MB/s
```
=> rust: Add benchmarks which compare to *ring* AES-128-GCM

rust/src/internals/block.rs
This results in a noticible speedup.
Before:
test bench::bench_aes_siv_128_encrypt_1024_bytes  ... bench:
4,149 ns/iter (+/- 385) = 246 MB/s
test bench::bench_aes_siv_128_encrypt_128_bytes   ... bench:
649 ns/iter (+/- 78) = 197 MB/s
test bench::bench_aes_siv_128_encrypt_16384_bytes ... bench:
63,147 ns/iter (+/- 3,339) = 259 MB/s
After:
test bench::bench_aes_siv_128_encrypt_1024_bytes  ... bench:
3,279 ns/iter (+/- 216) = 312 MB/s
test bench::bench_aes_siv_128_encrypt_128_bytes   ... bench:
551 ns/iter (+/- 82) = 232 MB/s
test bench::bench_aes_siv_128_encrypt_16384_bytes ... bench:
51,337 ns/iter (+/- 6,315) = 319 MB/s
=> rust: Use u128s to copy blocks

rust/src/internals/aes.rs, rust/src/internals/block.rs, rust/src/internals/block_cipher.rs, rust/src/internals/ctr.rs, rust/src/internals/mod.rs
Adds a `Block8` type for performing vectorized AES operations. Uses `Block8` to implement the internals of AES-CTR.
Provides an approximately 1.4X speedup (Unfortunately AES-CMAC can't be vectorized and becomes the bottleneck).
Before:
```
test bench::bench_aes_siv_128_encrypt_16384_bytes ... bench:
51,337 ns/iter (+/- 6,315) = 319 MB/s
```
After:
```
test bench::bench_aes_siv_128_encrypt_16384_bytes ... bench:
39,036 ns/iter (+/- 5,027) = 419 MB/s
```
=> rust: Use vectorized AES-NI to implement AES-CTR

rust/src/bench.rs, rust/src/internals/ctr.rs
This implementation goes approximately 4GB/sec on my i7, or about 0.8 cpb.
Benchmark included
=> rust: Faster AES-CTR implementation

rust/tests/lib.rs, rust/tests/test_vectors.rs, vectors/aes_pmac_siv.tjson
As **AES-PMAC-SIV** is effectively a novel construction, it has no existing test vectors to draw from.
This set of test vectors was created by using the same inputs as the **AES-SIV** test vectors, and running them against the Rust **AES-PMAC-SIV** implementation.
This implementation should be correct because:
1) **AES-PMAC** has been tested against Rogaway's test vectors
2) **AES-SIV** has been tested against several vectors
3) **AES-SIV** is implemented as a generic construction, letting us swap within a known-good **AES-SIV** implementation a known-good PMAC implementation.
Based on this, we use the Rust implementation as a reference, and generate test vectors from it in order to test correctness of the other language implementations.
=> vectors: AES-PMAC-SIV test vectors

go/block/block.go, go/block/block_test.go, go/pmac/pmac.go, go/pmac/pmac_aes_test.go
This adds an implementation of PMAC which provides the `hash.Hash` interface.
The implementation has been tested against the common set of AES-PMAC test vectors and passes.
This implementation presently is not vectorized. It looks like Go does not make it simple to use vectorized AES-NI, and vectorizing it would likely require using an ASM implementation instead of `cipher.Block`.
=> go: PMAC implementation

go/cmac/cmac.go, go/pmac/pmac.go
This package provides some abstractions which can be shared across CMAC and PMAC. PMAC is already implemented in terms of these abstractions.
This commit updates CMAC to use the block package, and makes some changes to PMAC for consistency across the two implementations, and hopefully a more Go-like style.
=> go: Refactor CMAC to use the block package

README.md
At Rogaway's suggestion, we have given AES-GCM-SIV a green heart:
https://github.com/miscreant/miscreant/pull/29
We have also given AES-GCM-SIV a sparkling heart for performance.
AES-SIV and AES-PMAC-SIV still have higher security bounds though.
This commit upgrades these ciphers' security level to a sparkling heart.
=> README.md: Ratchet up AES-SIV and AES-PMAC-SIV security levels

go/aead.go, go/aead_test.go, go/cmac/cmac.go, go/cmac/cmac_aes_test.go, go/siv.go, go/siv_test.go
Exposes the full AES-PMAC-SIV construction from the Go library, and tests it
against the shared test vectors.
=> go: Add AES-PMAC-SIV APIs

js/src/internal/polyfill/aes.ts, js/test/aes.spec.ts
This library does not utilize AES decryption, yet the provided AES polyfill
still has some leftover vestages of support for it.
This removes all remaining dead code for supporting AES decryption.
=> js: Gut remaining AES decryption functionality

js/README.md, js/src/internal/aes_siv.ts, js/src/internal/mac/pmac.ts, js/src/miscreant.ts, js/test/aes_pmac_siv.spec.ts, js/test/aes_siv.spec.ts, js/test/miscreant.spec.ts, js/test/support/test_vectors.ts
Implements the full AES-PMAC-SIV construction by adding support for switching
out the MAC used with the existing AES-SIV implementation.
Tests the resulting construction against the shared test vectors.
=> js: AES-PMAC-SIV implementation

ruby/.rubocop.yml, ruby/lib/miscreant/internals.rb, ruby/lib/miscreant/internals/block.rb, ruby/lib/miscreant/internals/mac/pmac.rb, ruby/lib/miscreant/internals/util.rb, ruby/spec/miscreant/internals/mac/pmac_spec.rb, ruby/spec/support/test_vectors.rb
Implements a (non-IUF) PMAC which matches the CMAC implementation.
Perhaps both the CMAC and PMAC implementations should be switched to IUF for consistency with the rest of the implementations.
Does not yet include the full AES-PMAC-SIV construction.
=> ruby: AES-PMAC implementation

ruby/.rubocop.yml, ruby/lib/miscreant/internals/siv.rb, ruby/spec/miscreant/internals/siv_spec.rb, ruby/spec/support/test_vectors.rb
Adds a parameter to `Miscreant::Internals::SIV` to specify `:CMAC` or `:PMAC` as the
MAC function.
Adds specs for the full AES-PMAC-SIV, which pass.
=> ruby: AES-PMAC-SIV implementation

ruby/README.md
* The `Miscreant::AES::SIV` namespace is now
`Miscreant::Internals::SIV`.
* The message given to `seal` must be binary encoded.
* The nonce given to `seal` and `open` must be an array.
=> ruby: Update README to use current interface

python/miscreant/aes/siv.py, python/tests/support/test_vectors.py, python/tests/test_aes_siv.py
Makes the MAC used by AES-SIV a parameter, and adds test cases for doing AES-SIV with PMAC.
=> python: PMAC-SIV support

rust/src/internals/block.rs
This function used to contain a pointer equality check, but it was removed in 462d4b190d5f5c0f294b27b6114dea8d64566602.  It's impossible for the two references to alias without UB, anyways.
=> rust: Update panic conditions for Block::copy_from_block

rust/Cargo.lock, rust/Cargo.toml, rust/src/bench.rs, rust/src/internals/aes.rs, rust/src/internals/ctr.rs, rust/src/internals/mac/cmac.rs, rust/src/internals/mac/mod.rs, rust/src/internals/mac/pmac.rs, rust/src/internals/mod.rs, rust/src/siv.rs, rust/tests/lib.rs
Results in a nice performance boost.
Before:
aes_ctr_128_encrypt_16384_bytes:       4,397 ns/iter (+/- 673)   = 3726 MB/s
aes_pmac_siv_128_encrypt_16384_bytes: 13,193 ns/iter (+/- 1,782) = 1241 MB/s
After:
aes_ctr_128_encrypt_16384_bytes:       2,834 ns/iter (+/- 616)   = 5781 MB/s
aes_pmac_siv_128_encrypt_16384_bytes: 11,382 ns/iter (+/- 2,029) = 1439 MB/s
=> rust: Use AES-CTR implementation from the 'aesni' crate

rust/Cargo.lock, rust/Cargo.toml, rust/src/ctr.rs, rust/src/lib.rs, rust/src/siv.rs
Removes the remaining usages of array_ref! which allows us to `#![deny(unsafe_code)]`
=> rust: Deny unsafe_code

rust/Cargo.lock, rust/Cargo.toml
Eliminate git dependencies for block-cipher-trait, crypto-mac, and aesni and replace them with released crates.
=> rust: Switch to released new RustCrypto crates

rust/Cargo.lock, rust/Cargo.toml, rust/src/aead.rs, rust/src/lib.rs, rust/src/s2v.rs, rust/src/siv.rs, rust/tests/aead_test.rs
This should make it easier to reuse for other purposes (e.g. KDF)
=> rust: Factor s2v() into its own module

rust/src/aead.rs
I cheated a bit with the initial AEAD implementation and used macros to define the various types.
This replaces it with a generic `SivAlgorithm` type which provides a generic implementation of `aead::Algorithm` for any `Siv` type.
=> rust: Replace macro-based AEAD implementation with a generic one

README.md
I tried adding a fourth tier in my heart powered gumball chart-style competitive analysis consisting of red 💔, yellow 💛, and green 💚 hearts, adding a SparklingHeart!™ 💖 to designate maximal awesomeness.
The SparklingHeart!™ 💖 unfortunately renders oddly on some platforms and may be overselling the things labeled with it (or underselling the things not labeled with it) and, in retrospect, just makes the chart more complicated and confusing (also resorting in ♣ as a typographic
dagger).
The resulting chart should be simpler, easier to interpret, and hopefully more fair to every algorithm listed.
=> README.md: Remove SparklingHeart!™ ratings

rust/src/stream.rs, rust/tests/stream_test.rs
These types were previously generic around nonce length, which was silly.
They are now hardcoded to accept a 64-bit nonce prefix.
=> rust: Remove generic nonce length from STREAM Encryptor/Decryptor

rust/src/aead.rs, rust/src/buffer.rs, rust/src/error.rs, rust/src/lib.rs, rust/src/s2v.rs, rust/src/siv.rs, rust/src/stream.rs, rust/tests/aead_test.rs, rust/tests/siv_test.rs, rust/tests/stream_test.rs
Buffer is a wrapper type for SIV message slices, which handles slicing them into the IV/tag portion and the plaintext/ciphertext portion.
=> rust: Add Buffer type

.travis.yml, rust/Cargo.toml, rust/src/aead.rs, rust/src/buffer.rs, rust/src/error.rs, rust/src/lib.rs, rust/src/siv.rs, rust/src/stream.rs, rust/tests/aead_test.rs, rust/tests/siv_test.rs, rust/tests/stream_test.rs
Adds a set of allocating APIs that correspond to each of the existing APIs, gated on an enabled-by-default "std" feature.
Uses these APIs in tests, which exercises both codepaths, and also makes the tests cleaner.
=> rust: "std" feature and allocating APIs

js/ci.sh
Out of nowhere this started happening:
./ci.sh: line 8: tsfmt: command not found
[See this build for an example](https://travis-ci.org/miscreant/miscreant/jobs/317040904)
Not sure why... typescript-formatter is being installed:
success Installed "typescript-formatter@7.0.0" with binaries:
I've confirmed locally that a `$ yarn add global typescript-formatter` installs the `tsfmt` executable. Ostensibly other packages we're installing globally, like `tslint`, are working.
So, disable `tsfmt` for now, and investigate later when we have time.
=> js/ci.sh: Disable tsfmt and tslint checks

rust/LICENSE-APACHE, rust/LICENSE-MIT, rust/README.md
I, Tony Arcieri, am the sole author of the Rust implementation of Miscreant, and as such, relicense all source code (i.e. code located under the "rust/" dicrectory of the repo) under both the MIT and Apache 2.0 licenses.
This change does not apply to the other language implementations (although that might be worth considering).
=> rust: Dual license under MIT/Apache 2.0

ruby/lib/miscreant.rb, ruby/lib/miscreant/stream.rb, ruby/spec/miscreant/stream_spec.rb, ruby/spec/support/test_vectors.rb
Implements the STREAM construction for online authenticated encryption as described in the paper "Online Authenticated-Encryption and its Nonce-Reuse Misuse-Resistance"[1]
This implementation is tested against the in-repo test vectors originally generated from the Rust implementation.
[1]: https://eprint.iacr.org/2015/189.pdf
=> ruby: STREAM implementation

js/README.md, js/src/aead.ts, js/src/exceptions/integrity_error.ts, js/src/exceptions/not_implemented_error.ts, js/src/index.ts, js/src/mac/cmac.ts, js/src/mac/pmac.ts, js/src/providers/polyfill.ts, js/src/providers/webcrypto.ts, js/src/siv.ts, js/test/aes_cmac.spec.ts, js/test/aes_pmac.spec.ts, js/test/aes_pmac_siv.spec.ts, js/test/aes_siv.spec.ts, js/test/aes_siv_aead.spec.ts
Ditches default classes anywhere in the public API
Exposes:
- CMAC
- PMAC
- WebCrypto and Polyfill provider classes
- Exception classes
=> js: Refactor to expose as much high-level functionality as possible

.travis.yml, rust/Cargo.lock, rust/Cargo.toml, rust/include/miscreant.h, rust/src/ffi.rs, rust/src/lib.rs, rust/tests/ffi/.gitignore, rust/tests/ffi/Makefile, rust/tests/ffi/ffi_test.c
Adds a C ABI which allows C/C++ or languages which support C ABI bindings to bind to the Rust implementation of Miscreant. See #107.
Also adds tests which ensure the C ABI is working as expected.
=> rust: Add C ABI (closes #107)

dotnet/README.md
I've moved the rest of the documentation that was previously in language-specific README files to the Wiki in order to improve collaboration and ease of editing.
=> dotnet/README.md: Move C# docs to the Wiki

js/package.json, js/yarn.lock
Updates all dependencies to the latest version.
However, node-webcrypto-ossl tests fail on the latest version, which may indicate an upstream regression. Lock it to the last known working version for now. We should investigate further.
=> js/package.json: Upgrade all dependencies except node-webcrypto-ossl

rust/src/aead.rs
This adds missing documentation for AEAD `open/seal_in_place`.
=> rust: docs for AEAD API

js/package.json, js/yarn.lock
Updates all build dependencies to the latest version. Including
node-webcrypto-ossl after tracking down why versions between 1.0.31
and 1.0.35 triggered a regression.
Fixes #154
=> js/package.json: Upgrade all devDependencies

go/siv.go
It appears there is a small typo on L#164
I believe "contruction" should be "construction."
Signed-off-by: Gaige Lama <gaigelama@gmail.com>
=> go: Fix small comment typo

.travis.yml, rust/Cargo.lock, rust/Cargo.toml, rust/README.md, rust/src/aead.rs, rust/src/bench.rs, rust/src/ctr.rs, rust/src/ffi.rs, rust/src/lib.rs, rust/src/s2v.rs, rust/src/siv.rs, rust/src/stream.rs, rust/tests/aead_test.rs, rust/tests/aead_vectors/mod.rs, rust/tests/siv_test.rs, rust/tests/siv_vectors/mod.rs, rust/tests/stream_test.rs, rust/tests/stream_vectors/mod.rs
This upgrades to the new `core::arch`-based aesni 0.3 crate, which drops its previous AES-CTR API, and so we use the one from the new block-modes crate.
The particular implementation in this change breaks the current API a bit in regard to the type signatures of heavily generic bits like `Siv` and `SivAlgorithm`. It'd be nice to refactor so as to introduce fewer type parameters, but this at least gets the crate(s) upgraded.
=> rust: Upgrade aesni crate to 0.3; use block-modes crate

.travis.yml
The build is presently broken because bits of the `no_std` API changed:
https://travis-ci.org/miscreant/miscreant/jobs/394811801
Miscreant will build on stable Rust as of tomorrow, and `nightly` is a moving target, so allow failures on `nightly` in the hope that we will be able to guarantee consistent, reproducible builds on stable.
=> rust: Allow failures on nightly

.travis.yml, rust/Cargo.lock, rust/Cargo.toml
When #177 is merged maybe we should add the non `aesni` backend on stable as well. This PR addresses #178
=> Making crate build on 1.27 stable

rust/README.md, rust/src/lib.rs
This fixes #178 and adds new documentation to the README and the crate root about rust requirements.
I hope this means a `crates.io` release soon :grin:
=> Fixing documentation about build instructions

rust/.gitignore, rust/Cargo.lock
We should always be able to build on the latest dependencies
=> rust: Remove Cargo.lock

rust/Cargo.toml
Otherwise the test fails due to the "bench" feature
Separately, we should really switch to criterion.rs
=> rust: Only build the `std` feature on docs.rs
